### PR TITLE
Code restructure/refactor

### PR DESCRIPTION
**Pull request by winterrdog**
**About the xor_encryptor.py:**

1. Combined and composed all the code into functions(Planning on making it Object-oriented).
2. Fixed the TypeError that was occurring after ord() was called on the individual bytes in the data parameter of the xor function(may have been caused by the the way Python 3 was interpreting bytes because it was giving ord() function arguments of data type 'int' yet ord() works on individual characters of strings).
3. Added more error handling around the code reading in the plain text bytes from the specified file at the command line.
4. Improved execution time.

**About the main.cpp:**

1. Added a memory allocation check on the VirtualAlloc() return value to prevent unintended program crashes.
2. Introduced a "key" variable to store the intended key/password to encrypt/decrypt during xoring of plain data
3. Fixed the shell-code's data type from signed char to unsigned char since binaries are made of unsigned characters

### CODE REVIEW

**Comment by 3ct0s** [comment]
This is a very interesting approach to make things better on the code. 
I would love to add this code to the main branch but because the current code is shown in my YouTube video, changing it would cause confusion. Since I am new to GitHub, is there a way of having both of these versions up on the same repo?

**Comment by winterrdog** [comment]
Thanks for the quick response! Maybe you can create a branch for this one instead(giving it a descriptive name of course), because a branch can allow you to develop new features, fix unseen bugs, or safely experiment with new ideas in a contained/isolated area of your repository.


use [_this_](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-branches) to learn how to create branches on Git

**Comment by 3ct0s** [comment]
That's great. How would you name this branch? And also how can I push this code into the new branch?
Let me know.

**Comment by winterrdog** [comment]
OK! i think lemme merge these changes to the new branch u just created.

**Comment by 3ct0s** [comment]
Sure, go for it. It's fine.

**Pull request merged**
